### ISSUE TITLE
Feature request: Switch to external link

### ISSUE THREAD

**Issue by abriggs-eduserv** [rasmusjp/umbraco-multi-url-picker#16]
Hi,

My client as ask me to pass on a feature request: Can you add an "External link" button next to the "Link to file" button to make the process of adding an external link more explicit?

Currently, once you've clicked on the content tree you have to close & re-open the dialog to enter an external link.

Thanks,

Antony

**Comment by rasmusjp** [comment]
Hi

I'm using the link picker dialog from the Umbraco Core, so it needs to be added there.
