### ISSUE TITLE
Feature request: Usage in macro parameter

### ISSUE THREAD

**Issue by RNRGFX** [rasmusjp/umbraco-multi-url-picker#22]
Nice package!
Would it be possible to add this to as a macro parameter? (I'm using macro's as widgets on a site)
I've tried to add "isParameterEditor: true" to package.manifest, and so far so good, it does work.
But when using in a macro container, and a link is selected, the umbraco panel is closed before I'm able to save the macro parameters:

Step 1:
![skaermbillede 2015-01-09 kl 10 42 35](https://cloud.githubusercontent.com/assets/7995554/5677893/83ebbc64-97ec-11e4-851d-89e6a4ab8e7c.png)

Step 2:
![skaermbillede 2015-01-09 kl 10 43 54](https://cloud.githubusercontent.com/assets/7995554/5677896/8ba0a0e6-97ec-11e4-8bcd-f10fe8e066da.png)

Step 3:
![skaermbillede 2015-01-09 kl 10 44 13](https://cloud.githubusercontent.com/assets/7995554/5677897/917080fe-97ec-11e4-9aad-066104820519.png)

Thanks!

**Comment by Myster** [comment]
Pull request contains 2 small tweaks to make this work as a macro parameter.
1) set the isParameterEditor: true 
 2) fix the auto closing issue.

**Comment by rasmusjp** [comment]
This is fixed in v1.3.0

**Comment by dreadpiratebrown** [comment]
How do I access the link data if I use this control in a macro? I created a Data Type, I added a macro parameter called "link1" that uses the new data type, and I tried declaring a variable in my macro partial view that uses that parameter, but I keep getting compilation errors.
