### ISSUE TITLE
question: How can I use use Multiurlpicker from my own controller/editor ?

### ISSUE THREAD

**Issue by rasmusfjord** [rasmusjp/umbraco-multi-url-picker#23]
Hey 

Im building a special grid property where i would really like to use your multiurlpicker as my url picker since im using it every where else in the solution.

How could i do this, or can this even be done ?

**Comment by rasmusjp** [comment]
Hi

Did you figure this out? I haven't used the grid yet so I'm not sure how to do this.

**Comment by rasmusfjord** [comment]
Jep i cooked a thing up. Basically by taking your great code in to a grid
type. ☺
Den 24/08/2015 22.00 skrev "Rasmus" <notifications@github.com>:
