### ISSUE TITLE
Courier project needs updating

### ISSUE THREAD

**Issue by shoecake** [rasmusjp/umbraco-multi-url-picker#24]
When I went to build the courier project with the lates version of courier, the interfsace to courier seems to have changed. In MultiUrlPickerDataResolverProvider.cs change

link.id = PersistenceManager.Default.GetUniqueId(

for

link.id = ExecutionContext.DatabasePersistence.GetUniqueId(

**Comment by rasmusjp** [comment]
Thanks. This has been updated.
