### ISSUE TITLE
Allow access to choose a media item when the user doesn't have access to media section

### ISSUE THREAD

**Issue by craigacronin** [rasmusjp/umbraco-multi-url-picker#30]
I currently have a limited set of users that I don't want them to be able to upload to the media section, due to naming conventions, folder destination etc etc.

I still want them to have the ability to choose a media item from this section, but it keeps prompting for a username and password.

**Comment by rasmusjp** [comment]
Hi

Since I'm using the link picker dialog from the Umbraco Core it seems to be a problem there,
