### ISSUE TITLE
Capitalisation of properties

### ISSUE THREAD

**Issue by danimalx** [rasmusjp/umbraco-multi-url-picker#33]
On my server version of a project the following code works:

 foreach (var item2 in multiUrlPicker)
                        {
						<a href="@item2.Url" target="@item2.Target" class="btn-default btn-paly">@item2.Name</a>
                      
						
                        }

However on my local version I can only retrieve properties with lower case, e.g.

		<a href="@item2.url" target="@item2.target" class="btn-default btn-paly">@item2.name</a>

Using Umbraco 7.2.6.

**Comment by rasmusjp** [comment]
It looks like you are getting the raw json back, is the RJP.MultiUrlPicker.dll present in the bin folder?

**Comment by danimalx** [comment]
I have fixed now, it was a coding error.
