### ISSUE TITLE
Links are wrong after being deployed in Umbraco.com

### ISSUE THREAD

**Issue by skttl** [rasmusjp/umbraco-multi-url-picker#34]
When I deploy some content with a Multi Url Picker in Umbraco.com, the links in ie. staging ends up being wrong.

I think it is because Multi Url Picker stores id's and they can be different from environment to environment.

Is it possible to use GUIDs instead?

**Comment by rasmusjp** [comment]
Changing the stored id's to Guid would be a breaking change, so i don't think it's a good idea right now.

You could try using Courier provider which located under src/RJP.MultiUrlPicker.Courier, you need to compile this yourself and reference it in your project.

I haven't used Umbraco.com yet, but i believe that it should work

**Comment by skttl** [comment]
Great, I'll try that. Thanks for your help!

med venlig hilsen
Søren Kottal




2015-10-02 14:13 GMT+02:00 Rasmus <notifications@github.com>:
