### ISSUE TITLE
Umbraco 7.4 - Display issue showing "{{cfg.minNumberOfItems-renderModel.length}}"

### ISSUE THREAD

**Issue by hfloyd** [rasmusjp/umbraco-multi-url-picker#40]
When installed in Umbraco 7.4 and placed onto a doctype, the display shows the Angular codes for Number of items. Also, if nothing has been selected in the Min/Max settings boxes, I think it shouldn't give you any message.
![rjp multiurlpicker-display-issue](https://cloud.githubusercontent.com/assets/1252593/13616214/e7f87dc0-e546-11e5-9236-d69c84ef10ac.png)

**Comment by rasmusjp** [comment]
This looks like a cache problem, could you try changing the version in /config/ClientDependency.config and see if it still is a problem.

**Comment by hfloyd** [comment]
Thank you, @rasmusjp, that did fix it. :-)
