### ISSUE TITLE
Umbraco 7.4 - Clicking "Add" button doesn't open dialog, instead causes frame reset.

### ISSUE THREAD

**Issue by hfloyd** [rasmusjp/umbraco-multi-url-picker#41]
In Umbraco 7.4, when added to a Doctype, the "Add" button doesn't work at all - if you click it, the right-pane of the content node resets to show the Content section main dashboard ("Get Started" tab, etc.).

In addition, this causes the loss of any unsaved property data in the node.

**Comment by rasmusjp** [comment]
This looks like a cache problem, could you try changing the version in /config/ClientDependency.config and see if it still is a problem.

**Comment by hfloyd** [comment]
Thank you, @rasmusjp, that did fix it. :-)
