### ISSUE TITLE
Feature request: More logging

### ISSUE THREAD

**Issue by ruant** [rasmusjp/umbraco-multi-url-picker#42]
Hi!
Would it be possible to add more logging to the log entry
"MultiUrlPicker value converter skipped a link as the node has been upublished/deleted (Id: ###), "
to include where it was skipped? So we can fix the dead link?

Cheers for a good tool.

**Comment by rasmusjp** [comment]
I would suggest adding `%aspnet-request{HTTP_HOST}%aspnet-request{PATH_INFO}` to the conversionPattern in the log4net.config, it will log the request url (if available) to every lentry in the log files.

e.g:

```xml
<layout type="log4net.Layout.PatternLayout">
  <conversionPattern value=" %date [P%property{processId}/D%property{appDomainId}/T%thread] %-5level %logger (%aspnet-request{HTTP_HOST}%aspnet-request{PATH_INFO}) - %message%newline" />
</layout>
```
