### ISSUE TITLE
Feature Request : Querystring Parameters 

### ISSUE THREAD

**Issue by jacqueswho** [rasmusjp/umbraco-multi-url-picker#45]
Hi @rasmusjp 

Great package by the way. Umbraco should make your picker as a new standard in the cms. Its absolutely fantastic. 

What would make it even more awesome is a single box for querystring parameters to add onto the url, wether its an external or internal link. This allows for flexibility. Maybe a add parameter button which allows you to add multiple key pair values

**Comment by mattbrailsford** [comment]
I could really do with this too

**Comment by mattbrailsford** [comment]
See PR #62
