### ISSUE TITLE
Doesn't work on Umbraco Cloud

### ISSUE THREAD

**Issue by sebastiandammark** [rasmusjp/umbraco-multi-url-picker#53]
**Umbraco version:** 7.5.13 assembly: 1.0.6309.16496
**Package version:** 1.3.2
![screen shot 2017-05-05 at 13 17 46](https://cloud.githubusercontent.com/assets/1575483/25743557/48319eba-3195-11e7-8b60-106d9747bb53.png)

The limitations text is visible and when I click "Add" I just end up on the Content dashboard
I haven't entered any limitations on the datatype.

**Comment by rasmusjp** [comment]
Usually it's because of client dependency caching.

Could you try to bumping the version in the ClientDependency.config?

**Comment by sebastiandammark** [comment]
Yep, that was it.
