### ISSUE TITLE
Multi Url Picker cant add nodes 

### ISSUE THREAD

**Issue by vishnushanmughan** [rasmusjp/umbraco-multi-url-picker#54]
The new version of Umbraco 7.6 supports MUP. But when its use inside an archetype an error throw by the MUP
![capture](https://cloud.githubusercontent.com/assets/28772646/26186823/0f6ff8e8-3bb2-11e7-8665-cdf64d9f5b32.PNG)

**Comment by rasmusjp** [comment]
Hey, just release v2.0.1 which should resolve this problem.
