### ISSUE TITLE
package.manifest not needed anymore?

### ISSUE THREAD

**Issue by ArnoldV** [rasmusjp/umbraco-multi-url-picker#58]
With the latest version of the Multi-Url Picker the datatype is broken if I use the NuGet version of the package since that adds a package.manifest file. If I remove it, things start to work again.

If I use the Umbraco package), the package.manifest is not created and everything works fine.

Is the package.manifest file not needed anymore?

**Comment by ArnoldV** [comment]
Hmm.. it might have something to do with our build server.. let me further investigate...

**Comment by rasmusjp** [comment]
From v2 the package.manifest isn't needed anymore, since the editor is registered in code.
I've checked the v2.0.1 NuGet zip file and the package.manifest isn't included.

Did you do an upgrade or a clean install?

**Comment by ArnoldV** [comment]
@rasmusjp, it's not included indeed.. but somehow this upgrade keeps giving me a package.manifest file.
Thanks for the clearup about if it's needed or not. Somewhere our build server is acting up then....
