### ISSUE TITLE
Unable to add external URL once internal link is picked

### ISSUE THREAD

**Issue by danbramall** [rasmusjp/umbraco-multi-url-picker#71]
Hi,

I have a situation whereby a client has added internal links to an RJP multi-URL picker property, but now wants to change them to external links.  The problem is that once a content editor has picked an internal link the 'Link' URL field is disabled and it's no longer possible to edit the URL manually.  I could be missing something but I couldn't find a way to 'deselect' the internal link in order to enable the Link URL field for manually inputting an external URL.

I guess the same issue arises if you want to just remove a link too.  Having picked a content page or media item you can't then undo that choice.

Ideally selecting an already-selected link would de-select it and re-enable the URL input field.

Thanks

**Comment by rasmusjp** [comment]
As @ronaldbarendse mentions, it's an issue with the Umbraco linkpicker which we are using, so it's not something I can easily fix.

I suggest removing the link and adding a new one instead.
