### ISSUE TITLE
Toggle query string and other options

### ISSUE THREAD

**Issue by ronaldbarendse** [rasmusjp/umbraco-multi-url-picker#75]
The query string is probably not needed by most editors and thus it should be possible to disable this field per data type (as pre value).

The query string field also allows adding a fragment/hash, so maybe this should be made clear by renaming it to 'Query string or hash' or just 'URL postfix'. Splitting this into 2 fields is probably overkill IMHO.

Currently, the overlay is based on the default Umbraco [linkpicker](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/common/overlays/linkpicker/linkpicker.html), so adding an option for `showTarget` should also be fairly simple.

Also (and this is something that should probably be changed in Umbraco itself) the order of fields could be improved, because selecting content or media overwrites any URL and/or name that is entered before that... As suggested by @greystate on the Umbraco Community Slack, the overlay could be reworked to look like this (personally, I would add the target as last):

![Linkpicker overlay mock-up](https://user-images.githubusercontent.com/1051287/38311855-75108e72-3820-11e8-829f-53d2476936ee.png)

The additional fields, like query string and target, could also be added as advanced options (like the redirect overlay of [Skybrud.Umbraco.Redirects](https://github.com/skybrud/Skybrud.Umbraco.Redirects); maybe even collapsed by default):

![redirects](https://user-images.githubusercontent.com/1051287/38311569-cb81fba2-381f-11e8-909d-1fc3a27001da.png)

**Comment by ronaldbarendse** [comment]
The built-in Umbraco link picker has changed in version 7.12.0, see:
- https://umbraco.com/blog/umbraco-version-712-release/
- http://issues.umbraco.org/issue/U4-4732

![Screenshot of new link picker dialog](https://umbraco.com/media/3872/anchor-links.png)

So adding/injecting/intercepting the custom query string isn't required anymore and actually breaks the layout:

![Screenshot of new link picker dialog with double query string](https://user-images.githubusercontent.com/1051287/44203211-8a067480-a14e-11e8-9735-008e8005da80.png)

**Comment by callumbwhyte** [comment]
This also broke my Meganav package - I fixed my link picker issue with one simple change: https://github.com/thecogworks/meganav/commit/6413dc0b81208eb79abd571d09afe6a6347d48a4

**Comment by callumbwhyte** [comment]
The link picker changes also broke my Meganav package in Umbraco v7.12 - I fixed the link picker issue with one simple change: https://github.com/thecogworks/meganav/commit/6413dc0b81208eb79abd571d09afe6a6347d48a4

**Comment by rasmusjp** [comment]
This should be fixed in v2.2.0
