### ISSUE TITLE
Multiple Links in Umbraco 7.12.3

### ISSUE THREAD

**Issue by Ric-Carey** [rasmusjp/umbraco-multi-url-picker#84]
Hi,

When you set the picker to have infinite mutiple links e.g: MinItems: 0 - MaxItems: -1. In Umbraco 7.12.3 - the link picker does not display. If you set maxItems to 1000 for example, it will then show.

Cheers

Ric

**Comment by rasmusjp** [comment]
If you leave both min and max empty, there shouldn't be any limit of how many links you can pick.

**Comment by Ric-Carey** [comment]
Hi Rasmus,

Ah yeah I see - used to the legacy MNTP of putting -1 in.

Thanks
