### ISSUE TITLE
Not working U v. 7.12.3

### ISSUE THREAD

**Issue by toporan** [rasmusjp/umbraco-multi-url-picker#85]
It does not seem to be working. When clicking on Add, the UI redirects to Get started dashboard.
Furthermore, the UI does not look right. See below. 

![riplink](https://user-images.githubusercontent.com/193939/46919936-1d411680-cfe7-11e8-83a8-b8fad66a063c.png)

**Comment by rasmusjp** [comment]
Looks like a caching problem, could you try bumping the client dependency version and see if that helps?

**Comment by toporan** [comment]
Clearing cookies and a hard reload "fixed" the problem.
Closing!
