### ISSUE TITLE
Can't edit anchor tag links

### ISSUE THREAD

**Issue by mniederkofler** [rasmusjp/umbraco-multi-url-picker#88]
I use the plugin to store anchor tags links in the main menu, using Umbraco Cloud 7.12.4 and Plugin 2.2.0.
I noticed an issue with the plugin when the links are edited.

It works fine to insert a link as long as I save the anchor link in the link field.
![image](https://user-images.githubusercontent.com/2385453/51314363-d0d6fe00-1a4f-11e9-8267-6699fd3ca482.png)

When I open the link again the anchor link is stored in the anchor field somehow. Now I am unable to save any changes (also to other fields, e.g. the link title) unless I copy the anchor field back to the link field. No exception occurs, it just doesn't save.
![image](https://user-images.githubusercontent.com/2385453/51314473-0bd93180-1a50-11e9-8481-b5c52d276421.png)

**Comment by rasmusjp** [comment]
Hmmm... this line might be the problem https://github.com/rasmusjp/umbraco-multi-url-picker/blob/c383d1cbe782aec125d675f574241a0a79404673/src/RJP.MultiUrlPicker.Web.UI/MultiUrlPicker.js#L83 I'll have a look at it this weekend and see if I can get a fix released.

**Comment by rasmusjp** [comment]
Sorry for the late response.

I've released a new version, 2.2.1, that fixes this issue.
