### ISSUE TITLE
Umbraco 8 Compatibility

### ISSUE THREAD

**Issue by 0Neji** [rasmusjp/umbraco-multi-url-picker#92]
I was wondering if there's any progress on compatibility with Umbraco 8? Did a search but couldn't find anything relating to this so apologies if it's been raised already.

Currently, it looks like the dependencies are set to Umbraco 7.6.0 or greater and less than 8.0.0 so I'm unable to install in to my project.

Thanks!

**Comment by rasmusjp** [comment]
I'm not going to upgrade this package to Umbraco 8, but I'm happy to tell you that it's been implemented in Umbraco Core from version 7.14 and 8. For docs see https://our.umbraco.com/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Multi-Url-Picker/
