### ISSUE TITLE
Trace Log reporting MultiUrlPicker value converter skipped a link as the node has been upublished/deleted

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [rasmusjp/umbraco-multi-url-picker#93]
How do we stop the trace logs reporting nodes that have been deleted or unpublished - especially when the node is deleted and therefore no longer in the database?

We are using Umbraco v 7.12.3 with MultiUrlPicker 1.3.1.

regards Fiona

**Comment by rasmusjp** [comment]
Hi Fiona

You can add a log4net filter to disable the logging, see https://github.com/rasmusjp/umbraco-multi-url-picker/issues/31#issuecomment-134362699 for more info

**Comment by HistoricEnglandDigitalTeam** [comment]
Thanks
